### ISSUE TITLE
How does nod differ from other signals&slots libraries?

### ISSUE THREAD

**Issue by cubuspl42** [fr00b0/nod#3]
What are the key differences between nod and many other similar solutions, especially nano?

**Comment by fr00b0** [comment]
Since the scope of the signal & slots construct is pretty narrow, you will find most of the differences are syntactical in nature.

The nod library is primarily designed to be easy to use, have a modern C++ feel to it, and above all be lightweight and only depend on the standard template library. Performance is __not__ the primary focus of the nod library. Many libraries out there sacrifice "syntactical sugar" for performance. Nod was developed as an alternative to using _boost.signal2_ in my own projects, just to avoid the massive dependency that using boost libraries can incur.

Compared specifically to nano there are a few points that are different, besides slightly different ways of doing things like connection management and retrieving slot return values.
 - Nod guarantees that slots are called in connection order.
 - Nod aims to provide thread safe signals by default, but also provide the possibility of single threaded only signals if needed.
